### ISSUE TITLE
Align-left and align-right are the same

### ISSUE THREAD

**Issue by neilprosser** [mikolajdobrucki/ikonate#11]
Just taking a look after seeing this pop up on HN. Nice work!

I noticed that (at least on ikonate.com) the align-left and align-right icons are the same.

<img width="378" alt="Screenshot 2019-04-19 at 10 35 40" src="https://user-images.githubusercontent.com/231666/56418474-e813ca80-628e-11e9-9c64-9299a8fd8963.png">

**Comment by mikolajdobrucki** [comment]
Thanks a lot for the heads up! Should be fixed now, both in the icons folder and in the app.
