### ISSUE TITLE
Crossing lines darker while opacity not full

### ISSUE THREAD

**Issue by woetroe0803** [mikolajdobrucki/ikonate#12]
When you set the color to #xxx9 you get not expected result as shown below. The expected result is that the whole icon is having the same color.

![image](https://user-images.githubusercontent.com/46375375/56421489-08e61b00-62a3-11e9-91df-718341e3062a.png)

Color setting:
![image](https://user-images.githubusercontent.com/46375375/56421517-274c1680-62a3-11e9-8a80-5897268120e9.png)

**Comment by mikolajdobrucki** [comment]
To change the opacity of the icon, I would suggest applying a desired opacity to the whole icon, rather than border's colour, e.g.:

```
.ikonate {
    opacity: .5;
}
```
