### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by phocke** [mikolajdobrucki/ikonate#13]
You mention `Built by @mikolajdobrucki & @mzaremski at ucreate` in the README.md and only `by @mikolajdobrucki & ucreate` on the landing page

**Comment by mikolajdobrucki** [comment]
That's because these were supposed to be links to Twitter profiles and at the time of writing this Marcin did not have a twitter account. @mzaremski feel free to add yourself to the list whenever you want ;)
