### ISSUE TITLE
"OK" and "OK-alt".svg images appear to be corrupt

### ISSUE THREAD

**Issue by Gamegenorator** [mikolajdobrucki/ikonate#6]
Both the "OK" and "OK-alt" images appear to be corrupt after downloading several times, I can find no program that will take them but will take the others. However, this only seems to affect the .svg formatted images in the download.

**Comment by mikolajdobrucki** [comment]
Took me quite a bit of time to realise what's the reason for this issue. It was related to a bug in a zipping package we use and a character "✓" that was used in descriptions. Should work as expected now

**Comment by Gamegenorator** [comment]
Ok, I would think the check with a circle should be called ok-alt or ok-circle instead of circle-ok but the problem is fixed now, thank you!

**Comment by mikolajdobrucki** [comment]
That's a very valid point actually 🤦‍♂ I will rename all the icons that follow this pattern in the next release
