### ISSUE TITLE
License Conflict

### ISSUE THREAD

**Issue by TylerBergNelson** [mikolajdobrucki/ikonate#8]
> Ikonate is available under the MIT. Feel free to use the set in both personal and commercial projects. Attribution in much appreciated but not required.

> Do not resell or redistribute the icons, even for free. If you share the set on the web, always link to the project's page, not directly to the file. Do not repost the file on other websites and services.

This does not make much sense. The MIT license explicitly allows resale and redistribution, even for free. Perhaps you were thinking of a Creative Commons variant?

**Edit:** Credit to mkl on [Hacker News](https://news.ycombinator.com/item?id=19696604) for noticing this.

**Comment by akdeb** [comment]
Updated here: https://github.com/mikolajdobrucki/ikonate/commit/e34fa97dd8295f538259f809632bdb74b2436250

**Comment by mikolajdobrucki** [comment]
Sorry for the confusion, everyone! I just removed the part of the README that didn't make any sense on this license.
